<?php
/**
 * Created by PhpStorm.
 * User: gong
 * Date: 4/9/2019
 * Time: 15:55
 */
namespace App\HttpController;
class Message extends Base{

    function index()
    {
        go(function (){
            /*
                注册一个名为queue的redis连接池
            */
            Redis::getInstance()->register('queue',new Config());
            /*
                实例化默认自带的Redis队列驱动
            */
            $driver = new RedisDirver('queue','queue');
            /*
                创建一个队列
            */
            $queue = new Queue($driver);

            /*
                生产者
            */
            go(function ()use($queue){
                while (1){
                    $job = new Job();
                    $job->setJobData(time());
                    $id = $queue->producer()->push($job);
                    var_dump('job create for Id :'.$id);
                    \co::sleep(3);
                }
            });
            /*
                消费者
             */
            go(function ()use($queue){
                $queue->consumer()->listen(function (Job $job){
                    var_dump($job->toArray());
                });
            });
        });
        parent::index(); // TODO: Change the autogenerated stub
    }
}