<?php
/**
 * Created by PhpStorm.
 * User: gong
 * Date: 4/9/2019
 * Time: 15:01
 */
namespace App\HttpController;
use EasySwoole\Annotation\Annotation;
use EasySwoole\Annotation\AbstractAnnotationTag;
use App\Service\A;
use App\Service\Param;
use App\Service\Timeout;
class Metadata extends Base
{
    function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
        /*
         * 实例化渲染器,并注册要解析的渲染方法
         */
        $annotation = new Annotation();
        $ref = new \ReflectionClass(A::class);
        //不注册fuck 解析
        $annotation->addParserTag(new Param());
        $annotation->addParserTag(new Timeout());

        $list = $annotation->getClassMethodAnnotation($ref->getMethod('test'));

        foreach ($list['param'] as $item){
            var_dump((array)$item);
        }

        foreach ($list['timeout'] as $item){
            var_dump((array)$item);
        }
    }
}